# Generated by Django 5.1.1 on 2024-10-19 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='items',
            new_name='cart',
        ),
    ]
