# Generated by Django 5.1.1 on 2024-10-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('sent', 'Order Sent'), ('received', 'Order Received'), ('ready', 'Order Ready'), ('delivered', 'Order Delivered')], default='sent', max_length=50),
        ),
    ]
