# Generated by Django 5.1.1 on 2024-10-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_items_orderhistory_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='cart',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='user_order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
