# Generated by Django 5.1.1 on 2024-10-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_orderhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='rider',
            field=models.CharField(choices=[('lcu_errands', 'LCU Errands'), ('greenbaba', 'Green Baba Delivery')], default='none', max_length=50),
        ),
    ]
