# Generated by Django 5.1.1 on 2024-10-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_orderhistory_cart_orderhistory_user_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='rider',
            field=models.CharField(choices=[('LCU Errands', 'lcu_errands'), ('Green Baba Delivery', 'greenbaba')], default='Not Picked', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('Sent', 'Order Sent'), ('Received', 'Order Received'), ('Ready', 'Order Ready'), ('Delivered', 'Order Delivered')], default='Sent', max_length=50),
        ),
    ]
