# Generated by Django 5.1.1 on 2024-10-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_orderhistory_rider_alter_orderhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='delivery',
            field=models.IntegerField(blank=True, default=400, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='service_fee',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
