# Generated by Django 5.1.1 on 2024-10-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orderhistory_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='rider',
            field=models.CharField(choices=[('LCU Errands', 'lcu_errands'), ('Green Baba Delivery', 'greenbaba')], default='none', max_length=50),
        ),
    ]
