# Generated by Django 5.1.1 on 2024-10-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_payment_delivery_payment_service_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='service_fee',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='total_amount',
        ),
    ]
