# Generated by Django 5.1.1 on 2024-10-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_payment_delivery_remove_payment_service_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='delivery',
            field=models.IntegerField(blank=True, default=400, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='service_fee',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
