# Generated by Django 5.1.1 on 2024-10-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_payment_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.ManyToManyField(blank=True, null=True, to='shop.cart'),
        ),
    ]
