# Generated by Django 5.1.1 on 2024-10-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_profile_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('cash', 'Cash on Delivery')], default='paystack', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
