# Generated by Django 5.1.1 on 2024-10-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_payment_order_id_payment_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
