# Generated by Django 5.1.1 on 2024-10-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_payment_payment_method_alter_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('cash', 'Cash on Delivery')], default='paystack', max_length=10),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('cash', 'Cash on Delivery')], default='paystack', max_length=10),
        ),
    ]
