# Generated by Django 5.1.1 on 2024-10-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_payment_delivered_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='items',
            field=models.ManyToManyField(blank=True, to='shop.cartitem'),
        ),
    ]
