# Generated by Django 5.1.1 on 2024-10-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_payment_method_orderhistory_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
