# Generated by Django 5.1.1 on 2024-10-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='delivery',
            field=models.IntegerField(blank=True, default=400, null=True),
        ),
    ]
