# Generated by Django 5.1.1 on 2024-10-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='delivered',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(blank=True, default='not ready', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
