# Generated by Django 5.1.1 on 2024-10-02 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_orderhistory_delivered_orderhistory_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.payment'),
        ),
    ]
