# Generated by Django 5.1.1 on 2024-10-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_orderhistory_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='rider',
            field=models.CharField(choices=[('lcu_errands', 'LCU Errands'), ('greenbaba', 'Green Baba Delivery')], default='Not Picked Up', max_length=50),
        ),
    ]
