# Generated by Django 5.1.1 on 2024-10-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
