# Generated by Django 5.1.1 on 2024-11-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_orderhistory_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('cash', 'Pay on Delivery')], default='paystack', max_length=10),
        ),
    ]
