# Generated by Django 5.1.1 on 2024-10-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_orderhistory_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
